finalproject/finalproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('rate/', include('rate.urls')),
    # Now, you should be able to access the reviews view at 
    # the URL http://yourdomain.com/rate/reviews/. 
    # Adjust the URLs based on your project structure and preferences.

        # path("", include("rate.urls")),
]

finalproject/rate/urls.py
from django.urls import path
from .views import all_reviews, category_list,category_detail
from .views import search_store, toggle_follow_store,toggle_like
from .views import user_profile,update_user_image, delete_review
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),

    path('categories/', category_list, name='category_list'),
    path('categories/<int:category_id>/', category_detail, name='category_detail'),

    path('search_store/', search_store, name='search_store'),
    
    path('stores/', views.store_list, kwargs={'sort_by':'date'},name='store_list'),
    path('stores_sorted/<str:sort_by>/', views.store_list, name='store_sorted'),


    path('stores/<int:store_id>/', views.store_profile, name='store_profile'),
    path('all_reviews/', views.all_reviews, name='all_reviews'),
    path('create_review/', views.create_review, name='create_review'),

    path('user_profile/<int:user_id>/', views.user_profile, name='user_profile'),


    path('update_user_image/', update_user_image, name='update_user_image'),

    
    path('toggle_follow/<int:store_id>/', toggle_follow_store, name='toggle_follow_store'),
    path('toggle_like/<int:review_id>/', toggle_like, name='toggle_like'),

    path('delete_review/<int:review_id>/', delete_review, name='delete_review'),


]

finalproject/rate/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# User Class: 
# Purpose: Represents a user in the system.
# Inheritance: Inherits from AbstractUser.
# Fields:Inherits fields from AbstractUser (provided by Django).
class User(AbstractUser):
    introduction = models.CharField(max_length=200,default='My introduction')
    image_url = models.URLField(default='https://cdn4.iconfinder.com/data/icons/music-ui-solid-24px/24/user_account_profile-2-512.png')

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    stores = models.ManyToManyField('Store', related_name='categories')
    image_url = models.URLField(max_length=200, null=True, blank=True, default="")

    def __str__(self):
        return self.name

class Store(models.Model):
    name = models.CharField(max_length=200)
    Joined_date = models.DateTimeField("date Joined")
    address = models.CharField(max_length=400)
    introduction = models.CharField(max_length=400)
    opening_time = models.TimeField()
    closing_time = models.TimeField()
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, related_name='store_categories')
    image_url = models.URLField(max_length=200, null=True, blank=True, default="")
    link_url = models.URLField(max_length=200, null=True, blank=True)
    star_rating = models.IntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=1)    
    
    def __str__(self):
        return self.name

#  has a follwer count and follower id , store id, 
class StoreFollowers(models.Model):
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    follower = models.ForeignKey(User, on_delete=models.CASCADE)
    # followers_count = models.PositiveIntegerField(default=0)
    def __str__(self):
        return f"{self.follower.username} follows {self.store.name}"


class FavoriteStore(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
  
    def __str__(self):
        return f"{self.user.username}'s favorite store: {self.store.name}"


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    content = models.TextField(max_length=500)
    spending = models.DecimalField(max_digits=10, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)
    image_url = models.URLField(max_length=500, null=True, blank=True)
    link_url = models.URLField(max_length=200, null=True, blank=True)
    likes = models.PositiveIntegerField(default=0)
    star_rating = models.IntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=1)
    def __str__(self):
        return f"{self.user.username}'s Review for {self.store.name}"


class LikeReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    # count=
    
    def __str__(self):
        return f"{self.user.username} likes {self.review}"


class CommentOnReview(models.Model):
    content = models.ForeignKey(Review, on_delete=models.CASCADE, related_name='comments')
    commenter = models.ForeignKey(User, on_delete=models.CASCADE)
    review_content = models.TextField(max_length=300)
    create_at = models.DateTimeField(auto_now_add=True)

finalproject/rate/forms.py
from django import forms
from .models import Review

# class ReviewForm(forms.ModelForm):
#     class Meta:
#         model = Review
#         fields = ['content', 'star_rating', 'spending', 'image_url', 'link_url']

class UpdateProfileForm(forms.Form):
    new_image_url = forms.URLField()

finalproject/rate/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from statistics import mean
from django.db import IntegrityError
from django.db.models import Count
from django.db.models import Q  # Import Q object for OR conditions
from django.contrib.auth.decorators import login_required

from django.views.generic.base import View
from django.http import JsonResponse
from django.urls import reverse
# from .forms import ReviewForm
from django.views.decorators.http import require_POST
from .models import User, Store, Review, FavoriteStore, Category
from .models import  LikeReview, CommentOnReview, StoreFollowers
from django.views import View
from django.shortcuts import render
from django.http import JsonResponse
from .forms import UpdateProfileForm



def index(request):
    # return render(request, "rate/index.html")
    reviews = Review.objects.all().order_by("-timestamp")

     # use pagination built-in function
    paginator = Paginator(reviews, 30)  # Show 10 posts per page
    page = request.GET.get('page')
    try:
        paginated_reviews = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        paginated_reviews = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g., 9999), deliver last page of results.
        paginated_reviews = paginator.page(paginator.num_pages)
    
    return render(request, 'rate/index.html', {'reviews': paginated_reviews})


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "rate/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "rate/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "rate/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "rate/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "rate/register.html")

# =============================
def category_list(request):
    categories = Category.objects.all()
    print(categories)
    context = {'categories': categories}
    return render(request, 'rate/category_list.html', context)

def category_detail(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    print(category)
    context = {'category': category}
    return render(request, 'rate/category_detail.html', context)


# For the store's profile to post new review
@login_required
def create_review(request):
    if request.method == "POST":
        print(request.POST)  # Add this line to print the POST data

        content = request.POST["content"]
        if content == '':
            content = "My reviews is empty"


        spending = request.POST["spending"]
        store_id = request.POST["store_id"]
        rating = request.POST["star_rating"]
        image_url = request.POST['image_url']
        # if image_url == '':
        #     image_url = ""
       
        user = request.user

        print(request)
        Review.objects.create(content=content, user=user, spending=spending, image_url=image_url,store_id=store_id, star_rating=rating)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, 'rate/create_review.html')

    # ==============================================

def all_reviews(request, ):
    reviews = Review.objects.all().order_by('-timestamp')

    for review in reviews:
        likes = LikeReview.objects.filter(review=review)
        review.like_count = len(likes)


    # Use pagination built-in function.
    paginator = Paginator(reviews, 32)  # Show 10 reviews per page.
    page = request.GET.get('page')
    try:
        paginated_reviews = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver the first page.
        paginated_reviews = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g., 9999), deliver the last page of results.
        paginated_reviews = paginator.page(paginator.num_pages)

    return render(request, 'rate/all_reviews.html', { 'reviews': paginated_reviews})



def store_list(request,sort_by):
    stores = Store.objects.all()#.order_by('-Joined_date')
    # return render(request, 'rate/store_list.html', {'stores': stores})

    for store in stores:
        reviews = Review.objects.filter(store=store)
        if len(reviews)>0:
            average_rating= mean([x.star_rating for x in reviews])
        else:
            average_rating=0

        store.average_rating=round(average_rating,1)
        store.review_count= len(reviews)


    # for the reverse order
    if sort_by == 'rating':
        stores= sorted(stores, key = lambda x: x.average_rating, reverse = True)
    elif sort_by == 'reviews':
        stores = sorted(stores, key = lambda x: x.review_count, reverse = True)
    else:
        stores = sorted(stores, key = lambda x: x.Joined_date, reverse = True)


    # Use pagination built-in function.
    paginator = Paginator(stores, 32)  # Show 10 reviews per page.
    page = request.GET.get('page')
    try:
        paginated_stores = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver the first page.
        paginated_stores = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g., 9999), deliver the last page of results.
        paginated_stores = paginator.page(paginator.num_pages)

    context={
        'stores':paginated_stores,
        'sort_by': sort_by,
    }

    return render(request, 'rate/store_list.html', context)

def store_profile(request, store_id):
    store = get_object_or_404(Store, id = store_id)
    reviews = Review.objects.filter(store = store).order_by('-timestamp')

    if request.user.is_anonymous:
        # user is not logged in 
        follow_button_text="Follow"
    else:
        store_follower_pair = StoreFollowers.objects.filter(
            follower=request.user)
        if store_follower_pair.exists():
            follow_button_text="Unfollow"
        else:
            follow_button_text="Follow"

    if len(reviews)>0:
        average_rating= mean([x.star_rating for x in reviews])
    else:
        average_rating=0

    store.average_rating=round(average_rating,1)
    store.review_count= len(reviews)

    all_followers =  StoreFollowers.objects.filter(store=store)
    follower_count=len(all_followers)

    for review in reviews:
        likes = LikeReview.objects.filter(review=review)
        review.like_count = len(likes)

    # Use pagination built-in function.
    paginator = Paginator(reviews, 10)  # Show 10 reviews per page.
    page = request.GET.get('page')
    try:
        paginated_reviews = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver the first page.
        paginated_reviews = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g., 9999), deliver the last page of results.
        paginated_reviews = paginator.page(paginator.num_pages)

    context = {
        "store":store,
        "follow_button_text":follow_button_text,
        "reviews":paginated_reviews,
        'follower_count':follower_count,
    }

    return render(request, 'rate/store_profile.html', context)

# ================================================

def user_profile(request, user_id):
    user = get_object_or_404(User, id = user_id)
    user_reviews = Review.objects.filter(user=user).order_by('-timestamp')

   
    # give the number of the like_count for the user profile page
    # reviews = Review.objects.filter(user=user).order_by('-timestamp')
    for review in user_reviews:
        likes = LikeReview.objects.filter(review=review)
        review.like_count = len(likes)


    paginator = Paginator(user_reviews, 10)
    page = request.GET.get('page')
    try:
        paginated_user_reviews = paginator.page(page)
    except PageNotAnInteger:
        paginated_user_reviews = paginator.page(1)
    except EmptyPage:
        paginated_user_reviews = paginator.page(paginator.num_pages)

    # Add the form for updating the profile image
    update_profile_form = UpdateProfileForm()

    context = {
        'user': user,
        'user_reviews': user_reviews,
        'paginated_user_reviews': paginated_user_reviews,
        'update_profile_form': update_profile_form,
    }

    return render(request, 'rate/user_profile.html', context)
    # ==============================================

@require_POST
@login_required
def update_user_image(request):
    user= request.user

finalproject/rate/templates/rate/all_reviews.html
<!-- rate/templates/rate/all_reviews.html -->
{% extends "rate/layout.html" %} {% load static %} {% block body %} 
{% block content %}


<div class="container mt-5 ">
  <div class="row">
    {% for review in reviews %}
    <!-- <div class="col-sm-4"> -->
      <div class="col-sm-3">
      <div style="background-color:darkcyan;color:white;padding:20px;">
      <p class="review_rate_stars">{{ review.star_rating }}</p>
      <p class="review_content">Review: {{ review.content }}</p>
      <p>{{ review.timestamp }}</p>
      <span hidden><h2> ID : {{ store.id }} </h2></span>
      <div><strong>
      <span>Posted by 
        <a style="color:bisque" 
        href="{% url 'user_profile' review.user_id %}"> {{ review.user }}  </a>
        <span>for</span>
        <a style="color:beige" 
        href="{% url 'store_profile' review.store.id %}"> {{ review.store.name }} </a>
      </span>
        </strong></div>

        {% if review.image_url != "" %}
        <img src="{{ review.image_url }}" alt="Image" width="20%" height="20%">
        {% endif %}
        
    </div>
   <br>
    </div>
    {% endfor %}
  </div>
</div>

<!-- pagination -->
<div class="container">
  <div class="d-flex justify-content-center">
    <div class="pagination">
      <span class="step-links">
        {% if reviews.has_previous %}
        <a href="?page=1">&laquo; First | </a>
        <a href="?page={{ reviews.previous_page_number }}"> previous</a>
        {% endif %}

        <span class="current">
          Page {{ reviews.number }} of {{ reviews.paginator.num_pages }}.
        </span>

        {% if reviews.has_next %}
        <a href="?page={{ reviews.next_page_number }}">Next | </a>
        <a href="?page={{ reviews.paginator.num_pages }}"> Last &raquo;</a>
        {% endif %}
      </span>
    </div>
  </div>
</div>

<br>

<script src="{% static 'rate/display_stars.js' %}"></script>
<script src="{% static 'rate/like_review.js' %}"></script>

{% endblock %} {% endblock %}

finalproject/rate/templates/rate/category_detail.html
<!-- rate/category_detail.html -->
{% extends 'rate/layout.html' %}  

{% block body %}
{% block content %}

<div class="container">
    <h2>{{ category.name }} list</h2>
    <ul>
        {% for store in category.store_categories.all %}
            <li><a href="{% url 'store_profile' store.id %}"><h3>{{ store.name }}</h3></a></li>
        {% endfor %}
    </ul>

 
    <button type="button" class="btn btn-primary btn-lg">
        <a class="btn btn-primary" href= "{% url 'category_list' %}" role="button">All stores</a>
    </button>
</div>


<img src="https://gettaphunter.com/wp-content/uploads/2016/03/feedback.jpg" 
width="460" height="200" style="width: 50%; height: auto; display: block;
margin-left: auto;
margin-right: auto;
width: 40%;">

{% endblock %}
{% endblock %}

finalproject/rate/templates/rate/store_profile.html
<!-- rate/templates/rate/store_profile.html -->
{% extends "rate/layout.html" %} {% load static %} {% block body %}

<!-- Place script inside the body tag -->
{% block content %}

<div class="p-5 mb-4 bg-body-tertiary rounded-3">
  <div class="container py-5">
    <h1 class="display-5 fw-bold">{{ store.name }}'s Profile</h1>
    <span hidden><h2>ID : {{ store.id }}</h2></span>
    <div class="review" data-post-id="{{ review.id }}">
      <img src="{{ store.image_url }}" width="300" height="300" style="border-radius:50%">

      <!-- <div class="card-body">
        <label for="newImageUrl">New Image URL:</label>
        <input type="text" id="id_new_image_url" name="new_image_url" placeholder="Enter new image URL">
        <button class="btn btn-primary" onclick="updateProfileImage()">Update Profile Image</button>
      </div> -->
    <hr>
      <br>
      <span class="review_rate_stars">{{ store.average_rating }}</span>
      <span>{{ store.average_rating}}
      <span>({{ store.review_count}})</span></span>
      <br>
      </div>

      <p class="card-text">Joined Date: {{ store.Joined_date }}</p>
      <p>Introduction: {{ store.introduction }}</p>
      <p>Opening Time: {{ store.opening_time }}</p>
      <p>Closing Time: {{ store.closing_time }}</p>
      <p>Address: {{ store.address }}</p>

      {% if user.is_authenticated %}
      <span>
        <button
          id="follow_store"
          type="button"
          class="btn btn-primary"
          onclick="handleToggleFollow({{store.id}})"
        >
          {{ follow_button_text }}
        </button>
      </span>
        {% endif %}

      <span id="followersCount">followers: 
        <span id="spanFollwerCount">{{ follower_count }}</span>
      </span>
      </div>
    </div>
  </div>
</div>
<br>
<hr />

<!--=================== Form for submitting reviews================== -->
<div class="container">
  <div class="store-container">
    <div class="card">
      <div class="card-body">
        <h4>Post your reviews</h4>
        <form method="post" action="{% url 'create_review' %}" class="was-validated">
          {% csrf_token %}

          <!-- hid the store id on the front-end -->
          <span hidden>
            <div class="form-group">
              <label for="store_id">store_id:</label>
              <input
                type="number"
                class="form-control"
                id="store_id"
                name="store_id"
                value="{{ store.id }}"
              />
            </div>
          </span>

          <div class="form-group" >
            <label for="content">Review Content:</label>
            <textarea
              class="form-control"
              id="content"
              name="content"
              rows="3"
              placeholder="Write your review here"
            ></textarea>
          </div>

          <div class="form-group">
            <label for="star_rating">⭐⭐⭐⭐⭐</label>
            <input
              type="number"
              class="form-control"
              id="star_rating"
              name="star_rating"
              min=1
              max=5
              value=""
            />
          </div>

          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text">$</span>
            </div>
            <!-- <div class="form-group"> -->
            <label for="spending"> </label>
            <input
              type="number"
              class="form-control"
              id="spending"
              name="spending"
              min="1.00"
              step="1.00"
              value="0.00"
              aria-label="Amount (to the nearest dollar)"
            />
          </div>

          <label for="basic-url"></label>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon3"
                >https://example.jpg(Gif/Png)</span
              >
            </div>
            <!-- <div class="form-group"> -->
            <label for="image_url"></label>
            <input
              type="url"
              class="form-control"
              id="image_url"
              name="image_url"
            />
          </div>

          <label for="basic-url"></label>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon3"
                >https://example.com</span
              >
            </div>
            <!-- <div class="form-group"> -->
            <label for="link_url"></label>
            <input
              type="url"
              class="form-control"
              id="link_url"
              name="link_url"
            />
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>
  </div>
</div>
<hr />
<!-- ========= Display All of the Reviews related the store ======================= -->

<div class="container mt-5 ">

    <h3>All the Reviews for this store that You might find helpfull</h3>
    <br>
    <div class="row">
    {% for review in reviews %}
    <div class="col-sm-4">
      <div style="background-color:darkcyan;color:white;padding:20px;">
        <ul>
          <div class="review" data-post-id="{{ review.id }}">
            <p class="review_rate_stars">{{ review.star_rating }}</p>
            <span>💰{{ review.spending }}
              &nbsp;&nbsp;
              <span>
                <img
                    src="{{ user.image_url }}"
                    alt="image"
                    width="50"
                    height="50"/>
            </span>
            </span>
            <p class="card-text">Posted by
              <a style="color:bisque" href="{% url 'user_profile' review.user_id %}">{{ review.user }}</a>
                for 
                <a style="color:bisque" href="{% url 'store_profile' review.store.id %}">{{ review.store.name }}</a>
                on {{ review.timestamp }}
            </p>
            &nbsp;
            <p>Review: {{ review.content }}</p>
            {% if review.image_url != "" %}
            <img src="{{ review.image_url }}" alt="iamge" width="100" height="100">
            {% endif %}
            <br>
            &nbsp;
            <div>
              <span
                class="like_button"
                onclick="handleToggleLike({{ review.id }})"
                style="cursor: pointer"
                >❤️</span>
              <span id="review_{{ review.id }}_like_count"
                >{{review.like_count}}</span>
            </div>
            <br>
            <hr>
          </div>
        </ul>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

<hr>

<!-- pagination -->
<div class="container">
  <div class="d-flex justify-content-center">
    <div class="pagination">
      <span class="step-links">
        {% if reviews.has_previous %}
        <a href="?page=1">&laquo; First | </a>
        <a href="?page={{ reviews.previous_page_number }}"> previous</a>
        {% endif %}

        <span class="current">
          Page {{ reviews.number }} of {{ reviews.paginator.num_pages}}
        </span>
        {% if context.has_next %}
        <a href="?page={{ reviews.next_page_number }}">Next | </a>
        <a href="?page={{ reviews.paginator.num_pages }}">
          Last &raquo;</a
        >
        {% endif %}
      </span>
    </div>
  </div>
</div>


<br />

<script src="{% static 'rate/display_stars.js' %}"></script>
<script src="{% static 'rate/like_review.js' %}"></script>
<script src="{% static 'rate/follow_store.js' %}"></script>

{% endblock %} {% endblock %}

finalproject/rate/templates/rate/user_profile.html
{% extends 'rate/layout.html' %}

<!-- Include the CSRF token -->
<script>
    var csrf_token = "{{ csrf_token }}";
</script>

{% load static %}

{% block body %}

{% block content %}

<div class="p-5 mb-4 bg-body-tertiary rounded-3">
    <div class="container py-5">
        <h1 class="display-5 fw-bold">{{ user.username }}'s' Profile</h1>
        <div class="review" data-post-id="{{ review.id }}">
            <img src="{{ user.image_url }}" width="200" height="200" style="border-radius:50%">
            <div class="card-body">
                <label for="newImageUrl">New Image URL:</label>
                <input type="text" id="id_new_image_url" name="new_image_url" placeholder="Enter new image URL">
                <button class="btn btn-primary" onclick="updateProfileImage()">Update Profile Image</button>
            </div>
            <hr>

            <br>
            <!-- <h4 class="card-title">Name: {{ user.username }}</h4> -->
            <p class="card-text">Joined Date: {{ user.date_joined }}</p>
            <p class="card-text">Address: {{ user.email }}</p>
            <p>Introduction : {{ user.introduction }}</p>
        </div>
    </div>
</div>

<hr>

<!--  Display all the posts from this user -->
<div class="container mt-5 ">
    <h3>All the posts from {{ user.username }}</h3>
    <div class="row"> 
        {% for review in user_reviews %}
        <div class="col-sm-4">
            <div style="background-color:darkcyan;color:white;padding:20px;">
                <ul>
                    <div class="reviews" data-post-id="{{ review.id }}">
                        <p class="review_rate_stars">{{ review.star_rating }}</p>
                        <p>💰 {{ review.spending }}</p>
                        <p>Content: {{ review.content }}</p>
                        <span><img src="{{ user.image_url }}" alt="image" width="20" height="20">
                            <span class="card-text">Posted by 
                                <a style="color:bisque" href="{% url 'user_profile' review.user_id %}"> 
                                {{ review.user }} </a>
                                for 
                                <a style="color:bisque" href="{% url 'store_profile' review.store.id %}">
                                {{ review.store.name }}
                                </a> on 
                                {{ review.timestamp }} 
                            </span>
                        </span>

                        <div>
                            {% if review.image_url != "" %}
                            <span><img src="{{ review.image_url }}" alt="Image" width="100" height="100">
                            {% endif %}
                        </span>

                        
                        <span class="like_button" onclick="handleToggleLike({{ review.id }})" 
                            style="cursor: pointer">❤️
                            <span id="review_{{ review.id }}_like_count">{{review.like_count}}  
                            </span>
                        </span>
                        </div>

                        <br>

                        <div>
                            <br>
                            <button id="delete_review" onclick="handleDeleteReview({{ review.id }})">Delete</button>
                            <hr style="color: aliceblue;">
                        </div>
                </ul>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<hr>

<!-- pagination -->
<div class="container">
    <div class="d-flex justify-content-center">
      <div class="pagination">
        <span class="step-links">
            {% if paginated_user_reviews.has_previous %}
            <a href="?page=1">&laquo; First |  </a>
            <a href="?page={{ paginated_user_reviews.previous_page_number }}">   previous</a>
            {% endif %}
  
            <span class="current">
                Page {{ paginated_user_reviews.number }} of {{ paginated_user_reviews.paginator.num_pages }}.
            </span>
            {% if paginated_user_reviews.has_next %}
            <a href="?page={{ paginated_user_reviews.next_page_number }}">Next |  </a>
            <a href="?page={{ paginated_user_reviews.paginator.num_pages }}">   Last &raquo;</a>
            {% endif %}
        </span>
    </div>
  </div>
</div>

<br>

<!-- Include the JavaScript file -->
<script src="{% static 'rate/display_stars.js' %}"></script> 
<script src="{% static 'rate/like_review.js' %}"></script> 
<script src="{% static 'rate/user_profile.js' %}"></script>
<script src="{% static 'rate/delete_review.js' %}"></script>
<!-- <script defer src="{% static 'rate/user_profile.js' %}"></script> -->



{% endblock %}
{% endblock %}